#!/usr/bin/env node
/**
 * esbuild build for dsh-im-gateway — emits BOTH halves of the plugin:
 *
 *   lib/index.js   node half   — the Cordis plugin entry (host-side).
 *   lib/client.js  browser half — a DSH client bundle aligned to the
 *                                 `window.__ModuleLoader__.load({id, factory})`
 *                                 contract that the web + client-modules loader
 *                                 fetches and executes (see
 *                                 packages/client/modules + tsdown.client.ts
 *                                 in the DSH checkout).
 *
 *   lib/vendor/lark-sdk.cjs
 *                vendored third-party — the Feishu/Lark SDK, bundled and
 *                checked in (see the block comment below for why).
 *
 * All `@deepseek-ai/*` packages and the React family stay external — they are
 * provided at runtime (host provides @deepseek-ai/*; the browser platform seed
 * provides react / @deepseek-ai/cordis). Node builtins are external under
 * platform 'node'.
 */

import { build } from 'esbuild'
import { mkdirSync, readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const outdir = join(root, '..', 'lib')
const require = createRequire(import.meta.url)

mkdirSync(outdir, { recursive: true })

// --- vendored third-party: the Feishu / Lark SDK ---
// WHY VENDORED: pnpm >= 10 refuses to run a *transitive* dependency's install
// script unless the consumer allowlists it, and the Feishu SDK hard-depends on
// `protobufjs`, whose `postinstall` (a purely cosmetic version-scheme warning)
// trips `ERR_PNPM_IGNORED_BUILDS`. That makes `dsh plugin add <git-url>` fail
// on a clean profile for every user, because dsh aborts when pnpm exits
// non-zero and the only remedy is editing the profile's pnpm-workspace.yaml.
// The published SDK dist is already a self-contained rollup/webpack bundle
// (`@larksuiteoapi/*` was external before only for *this* build) whose single
// remaining `require` is `protobufjs/minimal`, so bundling it once here keeps
// the entire install tree free of install-time scripts — no `allowBuilds`
// entry on any machine, ever. `scripts/check-install-scripts.mjs` guards that
// invariant for every other runtime dependency.
const larkManifestPath = require.resolve('@larksuiteoapi/node-sdk/package.json')
const larkManifest = require('@larksuiteoapi/node-sdk/package.json')
const larkEntry = join(dirname(larkManifestPath), 'lib', 'index.js')
const larkLicense = readFileSync(join(dirname(larkManifestPath), 'LICENSE'), 'utf8').trim()
const vendorDir = join(outdir, 'vendor')

mkdirSync(vendorDir, { recursive: true })
await build({
  entryPoints: [larkEntry],
  outfile: join(vendorDir, 'lark-sdk.cjs'),
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node20',
  minify: true,
  // Minification strips the upstream file's plain `/** MIT License ... */`
  // header (esbuild only preserves `/*!` / @license-style comments), so the
  // upstream LICENSE is carried explicitly in the banner below instead.
  legalComments: 'inline',
  sourcemap: false,
  banner: {
    js: `/*\n * VENDORED DEPENDENCY — @larksuiteoapi/node-sdk v${larkManifest.version} (MIT)\n * Upstream: https://github.com/larksuite/node-sdk\n * Generated by scripts/build.mjs from the published package — DO NOT EDIT BY HAND.\n * Regenerate with \`pnpm build\` (upgrade the devDependency to bump the version).\n *\n${larkLicense.split('\n').map(line => ` * ${line}`.trimEnd()).join('\n')}\n */`,
  },
  logLevel: 'info',
})

// --- node half ---
// Runtime deps are provided by the host (external @deepseek-ai/*) plus this
// plugin's own `dependencies` (ws, nodemailer, imapflow, mailparser), which
// resolve from node_modules at load time — never inline the heavy transports
// into the bundle. The Feishu SDK is *not* listed here: it is vendored into
// lib/vendor/lark-sdk.cjs and loaded from there at runtime (see above), so the
// feishu transport's dynamic import stays external through a path esbuild
// cannot statically resolve.
const nodeExternal = [
  '@deepseek-ai/*',
  'ws',
  'nodemailer',
  'imapflow',
  'mailparser',
  'bufferutil',
  'utf-8-validate',
]
await build({
  entryPoints: [join(root, '..', 'src', 'index.ts')],
  outfile: join(outdir, 'index.js'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  sourcemap: true,
  // Host-provided runtime deps: resolve from the DSH the plugin is loaded into.
  external: nodeExternal,
  logLevel: 'info',
})

// --- browser (client) half ---
// Align with the DSH client-modules contract: the bundle is one lazy CJS-ish
// factory handed to window.__ModuleLoader__.load({ id, factory }). The factory
// receives the injected `require` and resolves externals through the platform
// module table (react, @deepseek-ai/cordis), not through the filesystem.
await build({
  entryPoints: [join(root, '..', 'src', 'client', 'index.ts')],
  outfile: join(outdir, 'client.js'),
  bundle: true,
  platform: 'browser',
  format: 'cjs',
  target: 'es2020',
  sourcemap: true,
  jsx: 'transform',
  jsxFactory: 'React.createElement',
  jsxFragment: 'React.Fragment',
  // Platform table provides these at runtime; never bundle them.
  external: [
    'react',
    'react/*',
    'react-dom',
    'react-dom/*',
    '@deepseek-ai/*',
  ],
  banner: {
    js: `window.__ModuleLoader__.load({ id: 'dsh-im-gateway', factory: (require) => {
var module = { exports: {} }; var exports = module.exports;`,
  },
  footer: {
    js: `return module.exports
} })`,
  },
  logLevel: 'info',
})

console.log(`[build.mjs] emitted ${join(outdir, 'index.js')} and ${join(outdir, 'client.js')}`)
